### ISSUE TITLE
Can you please rename the download file

### ISSUE THREAD

**Issue by stoecker** [Jungle-Bus/josm-presets#1]
The JOSM presets must have an unique name. Now there is a conflict with preset.zip. Can you please adapt your download link, e.g.
Preset-Jungle-Bus.zip instead of preset.zip?

**Comment by nlehuby** [comment]
done

**Comment by nlehuby** [comment]
should i update some josm wiki page too or will be automatic ? :thinking:

**Comment by stoecker** [comment]
It's not automatic ;-)
